version: '3'
services:
  backend:
    image: viniciussoares18/sf-back:v1
    ports:
      - "8080:8081"
  nginx:
    image: viniciussoares18/sf-back-nginx:v2
    volumes:
      - /home/ubuntu/safe-food-infra-resources/ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - backend